# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#   Se impide para poder usar gemfile litesql
development:
  adapter: postgresql

  encoding: utf8

  database: publeddb
  host: localhost
  pool: 5

  username: publeduser

  password: fedesoft
